In [13]:
# Create a list of 1,000,000 salares ranging from 50,000 to 150,000
import random

salary_list = [random.randint(50000,150000) for _ in range(10_000_000)]

In [14]:
 import statistics

In [15]:
%%timeit
statistics.mean(salary_list)

2.55 s ± 301 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [16]:
import numpy as np

In [17]:
%%timeit
np.mean(salary_list)

615 ms ± 161 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [18]:
import numpy as np

In [20]:
my_array = np.array([1, 2, 3, 4])

In [22]:
my_array.mean()

2.5

In [30]:
# Job Titles
job_titleS = np.array(['Data Analyst', 'Data Scientist', 'Machines Learning Engineer', 'AI Engineer'])

# Base Salaries
base_salaries = np.array([60000, 80000, 75000, 90000, np.nan])

# Bonus Rates
bonus_rate = np.array([.05, .1, .08, .12, np.nan])

In [31]:
total_salaries = base_salaries * (1 + bonus_rate)

total_salaries

array([ 63000.,  88000.,  81000., 100800.,     nan])

In [33]:
np.nanmean(total_salaries)

83200.0

In [35]:
# Example: An array representing the number of years of experience required for three different data science job listings.
years_of_experience = np.array([1, 2, 3, 4])

In [36]:
years_of_experience_plus_one = years_of_experience + 1
years_of_experience_plus_one

array([2, 3, 4, 5])

In [37]:
years_of_experience_minus_one = years_of_experience - 1
years_of_experience_minus_one

array([0, 1, 2, 3])

In [38]:
years_of_experience_half = years_of_experience / 2
years_of_experience_half

array([0.5, 1. , 1.5, 2. ])

In [39]:
years_of_experience_double = years_of_experience *2
years_of_experience_double

array([2, 4, 6, 8])

In [40]:
second_and_third_jobs_experience = years_of_experience[1:3]
second_and_third_jobs_experience

array([2, 3])

In [42]:
jobs_with_more_than_one_year_experience = years_of_experience[years_of_experience > 2]
jobs_with_more_than_one_year_experience

array([3, 4])

In [43]:
import random

salary = [random.randint(50000, 150000) for num in range(10)]

In [44]:
salary

[127836, 114903, 137529, 53835, 93021, 72597, 55312, 86991, 62419, 118930]

In [46]:
salary_array = np.array(salary)
salary_array

array([127836, 114903, 137529,  53835,  93021,  72597,  55312,  86991,
        62419, 118930])

In [47]:
total_sum_salaries = np.sum(salary_array)
total_sum_salaries

923373

In [48]:
product_salaries = np.prod(salary_array)
product_salaries

-7785774115549132928

In [49]:
cumulative_sum_salaries = np.cumsum(salary_array)
cumulative_sum_salaries

array([127836, 242739, 380268, 434103, 527124, 599721, 655033, 742024,
       804443, 923373])

In [50]:
cumulative_prod_salaries = np.cumprod(salary_array)
cumulative_prod_salaries

array([              127836,          14688739908,     2020127710807332,
       -1926889130944591476,  5858314638869363676,  6383218625482279692,
       -2092958124963606336,   843758804195674944,  1126468649064465856,
       -7785774115549132928])

In [53]:
average_salary = np.mean(salary_array)
average_salary

92337.3

In [54]:
median_salary = np.median(salary_array)
median_salary

90006.0

In [56]:
salary_variance = np.var(salary_array, ddof=1)
salary_variance

965107154.9000001

In [57]:
salary_std_dev = np.std(salary_array, ddof=1)
salary_std_dev

31066.17380528217

In [58]:
min_salary = np.min(salary_array)
min_salary

53835

In [59]:
max_salary = np.max(salary_array)
max_salary

137529

In [61]:
salary_with_nan = np.array([123124, np.nan, 145000, 128000, 110000, 149999, np.nan, 135000, 115000, 140000], dtype=float)
salary_with_nan

array([123124.,     nan, 145000., 128000., 110000., 149999.,     nan,
       135000., 115000., 140000.])

In [62]:
salary_with_nan[salary_with_nan < 130000] = np.nan
salary_with_nan

array([    nan,     nan, 145000.,     nan,     nan, 149999.,     nan,
       135000.,     nan, 140000.])

In [64]:
salary_array = np.where(salary_array < 120000, 120000, salary_array)
salary_array

array([127836, 120000, 137529, 120000, 120000, 120000, 120000, 120000,
       120000, 120000])

In [65]:
# Generate numbers based on normal distribution
noise = np.random.normal(0, 5000, salary_array.size)
# Add these numbers to the salary_array
salary_array_With_noise = salary_array + noise
salary_array_With_noise

array([124610.13745866, 126179.74886955, 139637.37195121, 112471.7542639 ,
       123029.63883259, 127077.96812815, 119677.2297019 , 114401.36189318,
       119149.76433965, 122116.06201179])

# Problems

In [71]:
# Create NumPy Array
application_list = [10, 15, 7, 20, 25, 30, 5]

In [75]:
app_array = np.array(application_list)
app_array

array([10, 15,  7, 20, 25, 30,  5])

In [80]:
# Slicing Array
postings_list = [10, 15, 7, 20, 25, 30, 5]


In [83]:
posting_array = np.array(postings_list)
posting_array[1:5]

array([15,  7, 20, 25])

In [84]:
# Highest and Lowest Salary
salaries_list = [70000, 85000, 60000, 95000, 80000]

In [86]:
salary_array = np.array(salaries_list)
highest_salarie = np.max(salary_array)
lowest_salarie = np.min(salary_array)

print(highest_salarie)
print(lowest_salarie)

95000
60000


In [88]:
# Extra
interview_scores = [85, 90, 78, 92, 88, 76, 95]

array = np.array(interview_scores)
array

array([85, 90, 78, 92, 88, 76, 95])

In [89]:
applications_per_day = [12, 18, 25, 30, 10, 5, 8]
array = np.array(applications_per_day)
array[1:5]

array([18, 25, 30, 10])

In [90]:
candidate_ages = [24, 30, 27, 35, 22, 40, 28]
array = np.array(candidate_ages)
max_sal = np.max(array)
min_sal = np.min(array)

print(max_sal)
print(min_sal)

40
22


In [91]:
salaries_offered = [55000, 62000, 72000, 68000, 75000, 59000]
array = np.array(salaries_offered)

mean_sal = np.mean(array)
std_dev_sal = np.std(array, ddof=1)

print(mean_sal)
print(std_dev_sal)

65166.666666666664
7782.458908768273


In [92]:
all_salaries = [50000, 67000, 72000, 64000, 80000, 55000]
array = np.array(all_salaries)

more_than_65 = np.where(array > 65000, True, False)
more_than_65

array([False,  True,  True, False,  True, False])